// <auto-generated />
using System;
using AzulTracker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzulTracker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AzulTracker.API.Models.ExerciseLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubmittedById")
                        .HasColumnType("int");

                    b.Property<int?>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedById");

                    b.ToTable("ExerciseLibrary");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ExerciseMuscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseLibraryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("MuscleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseLibraryId");

                    b.HasIndex("MuscleId");

                    b.ToTable("ExerciseMuscles");
                });

            modelBuilder.Entity("AzulTracker.API.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleGroup = "Chest",
                            Name = "Pectoralis Major"
                        },
                        new
                        {
                            Id = 2,
                            MuscleGroup = "Chest",
                            Name = "Pectoralis Minor"
                        },
                        new
                        {
                            Id = 3,
                            MuscleGroup = "Back",
                            Name = "Latissimus Dorsi"
                        },
                        new
                        {
                            Id = 4,
                            MuscleGroup = "Back",
                            Name = "Rhomboids"
                        },
                        new
                        {
                            Id = 5,
                            MuscleGroup = "Back",
                            Name = "Erector Spinae"
                        },
                        new
                        {
                            Id = 6,
                            MuscleGroup = "Back",
                            Name = "Teres Major"
                        },
                        new
                        {
                            Id = 7,
                            MuscleGroup = "Shoulders",
                            Name = "Lateral Deltoid"
                        },
                        new
                        {
                            Id = 8,
                            MuscleGroup = "Shoulders",
                            Name = "Anterior Deltoid"
                        },
                        new
                        {
                            Id = 9,
                            MuscleGroup = "Shoulders",
                            Name = "Posterior Deltoid"
                        },
                        new
                        {
                            Id = 10,
                            MuscleGroup = "Shoulders",
                            Name = "Trapezius"
                        },
                        new
                        {
                            Id = 11,
                            MuscleGroup = "Shoulders",
                            Name = "Rotator Cuff"
                        },
                        new
                        {
                            Id = 12,
                            MuscleGroup = "Arms",
                            Name = "Biceps Brachii"
                        },
                        new
                        {
                            Id = 13,
                            MuscleGroup = "Arms",
                            Name = "Brachialis"
                        },
                        new
                        {
                            Id = 14,
                            MuscleGroup = "Arms",
                            Name = "Triceps Brachii"
                        },
                        new
                        {
                            Id = 15,
                            MuscleGroup = "Arms",
                            Name = "Forearms"
                        },
                        new
                        {
                            Id = 16,
                            MuscleGroup = "Core",
                            Name = "Rectus Abdominis"
                        },
                        new
                        {
                            Id = 17,
                            MuscleGroup = "Core",
                            Name = "Obliques"
                        },
                        new
                        {
                            Id = 18,
                            MuscleGroup = "Core",
                            Name = "Transverse Abdominis"
                        },
                        new
                        {
                            Id = 19,
                            MuscleGroup = "Core",
                            Name = "Serratus Anterior"
                        },
                        new
                        {
                            Id = 20,
                            MuscleGroup = "Legs",
                            Name = "Quadriceps"
                        },
                        new
                        {
                            Id = 21,
                            MuscleGroup = "Legs",
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 22,
                            MuscleGroup = "Legs",
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 23,
                            MuscleGroup = "Legs",
                            Name = "Abductors"
                        },
                        new
                        {
                            Id = 24,
                            MuscleGroup = "Glutes",
                            Name = "Gluteus Maximus"
                        },
                        new
                        {
                            Id = 25,
                            MuscleGroup = "Glutes",
                            Name = "Gluteus Medius"
                        },
                        new
                        {
                            Id = 26,
                            MuscleGroup = "Calves",
                            Name = "Gastrocnemius"
                        },
                        new
                        {
                            Id = 27,
                            MuscleGroup = "Calves",
                            Name = "Soleus"
                        });
                });

            modelBuilder.Entity("AzulTracker.API.Models.ProgramDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("ProgramDays");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ProgramExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomExerciseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExerciseLibraryId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ProgramDayId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseLibraryId");

                    b.HasIndex("ProgramDayId");

                    b.ToTable("ProgramExercises");
                });

            modelBuilder.Entity("AzulTracker.API.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("AzulTracker.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredWorkoutView")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RestTimerEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AzulTracker.API.Models.VideoUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("VideoUrls");
                });

            modelBuilder.Entity("AzulTracker.API.Models.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramExerciseId")
                        .HasColumnType("int");

                    b.Property<int?>("RPE")
                        .HasColumnType("int");

                    b.Property<int>("RepsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ProgramExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ExerciseLibrary", b =>
                {
                    b.HasOne("AzulTracker.API.Models.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ExerciseMuscle", b =>
                {
                    b.HasOne("AzulTracker.API.Models.ExerciseLibrary", "ExerciseLibrary")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseLibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AzulTracker.API.Models.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseLibrary");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ProgramDay", b =>
                {
                    b.HasOne("AzulTracker.API.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("ProgramDays")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ProgramExercise", b =>
                {
                    b.HasOne("AzulTracker.API.Models.ExerciseLibrary", "ExerciseLibrary")
                        .WithMany()
                        .HasForeignKey("ExerciseLibraryId");

                    b.HasOne("AzulTracker.API.Models.ProgramDay", "ProgramDay")
                        .WithMany("ProgramExercises")
                        .HasForeignKey("ProgramDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseLibrary");

                    b.Navigation("ProgramDay");
                });

            modelBuilder.Entity("AzulTracker.API.Models.TrainingProgram", b =>
                {
                    b.HasOne("AzulTracker.API.Models.User", "User")
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AzulTracker.API.Models.VideoUrl", b =>
                {
                    b.HasOne("AzulTracker.API.Models.User", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AzulTracker.API.Models.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("AzulTracker.API.Models.WorkoutLog", b =>
                {
                    b.HasOne("AzulTracker.API.Models.ProgramExercise", "ProgramExercise")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("ProgramExerciseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AzulTracker.API.Models.User", "User")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProgramExercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ExerciseLibrary", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("AzulTracker.API.Models.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ProgramDay", b =>
                {
                    b.Navigation("ProgramExercises");
                });

            modelBuilder.Entity("AzulTracker.API.Models.ProgramExercise", b =>
                {
                    b.Navigation("WorkoutLogs");
                });

            modelBuilder.Entity("AzulTracker.API.Models.TrainingProgram", b =>
                {
                    b.Navigation("ProgramDays");
                });

            modelBuilder.Entity("AzulTracker.API.Models.User", b =>
                {
                    b.Navigation("TrainingPrograms");

                    b.Navigation("WorkoutLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
