trigger:
  branches:
    include:
      - main
      - dev

pr:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build & Restore'
    jobs:
      - job: BuildAPI
        displayName: 'Build ASP.NET Core API'
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET 10'
            inputs:
              packageType: 'sdk'
              version: '10.x'

          - script: dotnet restore
            displayName: 'Restore NuGet packages'
            workingDirectory: '$(Build.SourcesDirectory)'

          - script: dotnet build AzulTracker.slnx --no-restore --configuration Release
            displayName: 'Build API'
            workingDirectory: '$(Build.SourcesDirectory)'

          - script: dotnet test --no-build --verbosity normal
            displayName: 'Run unit tests'
            workingDirectory: '$(Build.SourcesDirectory)/AzulTracker.Tests'

      - job: BuildFrontend
        displayName: 'Build React Frontend'
        steps:
          - task: UseNode@1
            displayName: 'Use Node.js'
            inputs:
              version: '20.x'

          - script: npm install
            displayName: 'Install npm packages'
            workingDirectory: 'AzulTracker.Frontend'

          - script: npm run build
            displayName: 'Build Frontend'
            workingDirectory: 'AzulTracker.Frontend'